var request = require('request');
var fs = require('fs');

function notify(ip, title, msg, image, duration) {

	var formData = {
		filename: (image.includes(':') == 1) ? {value: request(image), options: {contentType: 'application/octet-stream'}} : {value: fs.createReadStream(image), options: {contentType: 'application/octet-stream'}},
		// filename: {value: fs.createReadStream(image), options: {contentType: 'application/octet-stream'}},
		type: '0',                 // Always 0?
		offset: '0',               // Always 0?
		position: '2',             // 0=bottom-right, 1=bottom-left, 2=top-right, 3=top-left, 4=center
		transparency: '0',         // 0=default, 1=0%, 2=25%, 3=50%, 4=75%, 5=100%
		force: 'true',             // Always true?
		interrupt: 'false',        // If set, the notification is interactive and can be dismissed or selected to display more details. Depending on the running app (e.g. Netflix), this may stop playback.
		bkgcolor: '#607d8b',       // Background color of the notification, given in hex format.
		duration: duration,        // The duration in seconds for which the notification will be displayed.
		app: 'Node.js',            // App name to display the notification as generated by
		title: title,              // Title of notification
		msg: msg                   // Message to show
	};

	request.post({url:'http://'+ip+':7676', formData: formData}, function optionalCallback(err, httpResponse, body) {
		if (err) return console.error('Notify failed:', err);
		else console.log('Notify successful!  (%s)', httpResponse.statusCode);
	});

}

module.exports = notify;

// Exmaple:
// notify('192.168.1.64', 'Stock Alert', "Stock Price Watch: $118.25 as of "+Date(), "stock.png", "15")
